apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.name}}
  labels:
    app: {{.Values.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
      labels:
        app: {{.Values.name}}
    spec:
      containers:
      - name: {{.Values.name}}
        image:  {{.Values.deployment.image}}:{{.Values.deployment.tag}}
        ports:
          - containerPort: 80
        env:
        - name: REACT_APP_API_BASE_URL
          value: http://stakater-backend-service.com
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-service
spec:
  selector:
    app: {{.Values.name}}
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      